### ISSUE TITLE
glfw.Init() changes os.Getwd() to `./resources/` directory when one exists.

### ISSUE THREAD

**Issue by robertsdionne** [go-gl/glfw3#340]
macOS Monterey
go1.17.2

Make a project with the following layout:
```
resources/
go.mod
main.go
```

`main.go`:
```golang
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/go-gl/glfw/v3.3/glfw"
)

func main() {
	err := glfw.Init()
	if err != nil {
		log.Println(err)
	}

	fmt.Println(os.Getwd())
}
```

```bash
pwd
/Users/$USER/repro

# current working directory incorrectly changes to ./resources
go build .
go run ./repro
/Users/$USER/repro/resources <nil>

# strangely, go run works correctly
go run main.go
/Users/$USER/repro <nil>

# removing resources works correctly
rmdir resources
./repro
/Users/$USER/repro <nil>
```

Whereas, the modified program without glfw works correctly:
```golang
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println(os.Getwd())
}
```

```bash
mkdir resources
go build .
./repro
/Users/$USER/repro <nil>
```

**Comment by robertsdionne** [comment]
Probably caused by https://github.com/go-gl/glfw/blob/62640a716d485dcbf341a7c187227a4a99fb1eba/v3.3/glfw/glfw/src/cocoa_init.m#L35-L69

**Comment by dmitshur** [comment]
As suggested above, this is GLFW working as intended rather than a bug to be fixed. See https://www.glfw.org/docs/latest/intro_guide.html#GLFW_COCOA_CHDIR_RESOURCES_hint.

This behavior can be controlled via the [`CocoaChdirResources`](https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#CocoaChdirResources) init hint.
