### ISSUE TITLE
No error handling in v3.3

### ISSUE THREAD

**Issue by soypat** [go-gl/glfw3#368]
[`GLFWerrorfun glfwSetErrorCallback	(	GLFWerrorfun 	callback	)`](https://www.glfw.org/docs/latest/group__init.html#gaff45816610d53f0b83656092a4034f40) was removed from this implementation after 3.1. It apparently is still part of GLFW. Can it be added again?

I am available to contribute this feature but I'd need some guidance on where it goes. An example of a similar function in this repo would help out tremendously. Keep in mind I've never really worked with CGo.

**Comment by soypat** [comment]
Alright, after a cursory search of this package I found there is error handling, but it happens under the covers. Why is this package handling the errors? Why is the client not in control as per GLFW's spec?

**Comment by dmitshur** [comment]
go-gl/glfw generally follows the GLFW C API quite closely, but it's a Go package with an API that's meant to be more Go-like and friendly. As such, GLFW function calls that can fail return multiple values in the Go API, the last one being of type `error`.

For example, [`glfw.CreateWindow`](https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#CreateWindow) returns `(*glfw.Window, error)`. The error value is non-nil whenever the error callback indicated that there was an error during window creation. So the calling code gets to be in control over error handling:

```Go
window, err := glfw.CreateWindow(640, 480, "test", nil, nil)
if err != nil {
	// Handle the error as needed for your application.
}
```

(If you're looking for more a more complete example, see https://github.com/go-gl/example.)

**Comment by Jacalz** [comment]
There are a quite a few cases where we actually panic instead of return an error (https://github.com/search?q=repo%3Ago-gl%2Fglfw+panic+path%3A%2F%5Ev3.3%5C%2Fglfw%5C%2F%2F&type=code). I am personally of the opinion that libraries never should panic (unless if it perhaps is absolutely impossible to continue) and that it's up to the developer using the API to decide about it.

I know we have some code in Fyne that does a `defer func() { if r = recover(); r != nil }` to avoid the possible panics that can occur when polling events and getting clipboard data (https://github.com/search?q=repo%3Afyne-io%2Ffyne%20recover&type=code). These panics don't necessarily seem to warrant more than returning an error in my opinion. I'd be in favour of returning some more errors and do less panics.

**Comment by dmitshur** [comment]
I agree that returning an error to the caller, when the caller can reasonably handle it, is a common practice for Go libraries. https://go.dev/s/style#dont-panic covers this. https://go.dev/doc/effective_go#panic adds relevant context:

> The usual way to report an error to a caller is to return an error as an extra return value. [...] But what if the error is unrecoverable? Sometimes the program simply cannot continue.
>
> For this purpose, there is a built-in function `panic` [...] It's also a way to indicate that something impossible has happened, such as exiting an infinite loop.
>
> [...] If the problem can be masked or worked around, it's always better to let things continue to run rather than taking down the whole program. [...]

My understanding is that glfw v3.3 aims to follow exactly that. The current error handling behavior in v3.3 (which was inherited from v3.2) is documented at https://github.com/go-gl/glfw#glfw-32-specfic-changes:

> The error callback is now set internally. Functions return an error with corresponding code and description (do a type assertion to glfw3.Error for accessing the variables) if the error is recoverable. If not a panic will occur.

This was a deliberate design that we settled on after a good deal of discussion and considering trade-offs (it should be possible to find it in this project's history). I think it has been working well in general.

> possible panics that can occur when polling events and getting clipboard data

Can you please file two separate issues for those, and any other cases where we might've missed instances of recoverable errors not being handled optimally? That way we can use the issues to look into specifics.

I'll close this issue since v3.3 does do error handling and tries its best to return recoverable errors to the caller when it makes sense to, and intentionally doesn't return errors when they're deemed to be unrecoverable.

**Comment by Jacalz** [comment]
I see. Just wanted to move this issue along. Sorry if I fussed about it unnecessarily. Did a git blame and found out that it relates to https://github.com/fyne-io/fyne/issues/743. Will dig into it and see if it still is an issue that we need to workaround. If not, we can remove the recovers and be happy with what this package is doing :)
